Update patch set 3
Patch Set 3:

with this commit users report fatal exceptions like this when trying to send mms:

java.lang.NullPointerException: WorkingMessage.send MMS sending failure. mms_config.xml is missing uaProfUrl setting.  uaProfUrl is required for MMS service, but can be absent for SMS

http://hastebin.com/elohufujag.avrasm

Patch-set: 3
Reviewer: Tobias Teschner <12876@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0