Update patch set 4
Patch Set 4:

build error again

packages/apps/Mms/src/com/android/mms/ui/ComposeMessageActivity.java:2007: error: method getInt in interface SharedPreferences cannot be applied to given types;
        int unicodeStripping = prefs.getInt(MessagingPreferenceActivity.UNICODE_STRIPPING,
                                    ^
  required: String,int
  found: String,String
  reason: actual argument String cannot be converted to int by method invocation conversion
packages/apps/Mms/src/com/android/mms/ui/ComposeMessageActivity.java:2010: error: incomparable types: int and String
        if (unicodeStripping != MessagingPreferenceActivity.UNICODE_STRIPPING_LEAVE_INTACT) {
                             ^
packages/apps/Mms/src/com/android/mms/ui/ComposeMessageActivity.java:2012: error: incomparable types: int and String
                    unicodeStripping == MessagingPreferenceActivity.UNICODE_STRIPPING_NON_DECODABLE;
                                     ^

Patch-set: 4